volumes:
  padariaDB:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: fromtechadmin
      POSTGRES_DB: padariaDB

    ports:
      - "5432:5432"

    volumes:
      - padariaDB:/var/lib/postgresql/data

