--CRIAR FUNÇÃO PARA A TRIGGER ACIONAR
CREATE FUNCTION fn_atualizarValorPedido()
RETURNS TRIGGER AS $$
BEGIN
	--ATUALIZA O CAMPO VALOR COM O PREÇO DO PRODUTO CORRESPONDENTE
	SELECT PRECO INTO NEW.VALOR
	FROM PRODUTOS
	WHERE ID = NEW.idProduto;

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;


--CRIANDO A TRIGGER
CREATE TRIGGER tg_atualizarValorPedido
BEFORE INSERT OR UPDATE ON PEDIDOS
FOR EACH ROW
EXECUTE FUNCTION fn_atualizarValorPedido();